define player = Character("[player_name]", color="#fff")

define accountant = Character("Akira")
define baker = Character("Blake")
define banker = Character("Banner")
define caregiver = Character("Carol")
define expert = Character("Expert", expert="expert")
define facilitator = Character("Facilitator ", image="facilitator")
define guide = Character("Guy")
define janitor = Character("Janet")
define journalist = Character("Jorge")
define lawyer = Character("Luke")
define musician = Character("Mu")
define painter = Character("Payne")
define pianist = Character("Ray")
define student = Character("Student", image="student")
define surgeon = Character("Susan")
define teacher = Character("Téa")
define trainer = Character("Trainer", image="trainer")
define veteran = Character("Victor")
