define player = Character("[player_name]", color="#fff")

define accountant = Character("Akira")
define athlete = Character("Atlas")
define baker = Character("Blake")
define banker = Character("Banner")
define caregiver = Character("Carol")
define facilitator = Character("Tate", image="facilitator")
define expert = Character("Hex")
define guide = Character("Guy")
define janitor = Character("Janet")
define journalist = Character("Jorge")
define lawyer = Character("Luke")
define musician = Character("Mu")
define painter = Character("Payne")
define pianist = Character("Ray")
define student = Character("Stewie")
define surgeon = Character("Susan")
define teacher = Character("Téa")
define veteran = Character("Victor")
