define player = Character("[player_name]", color="#fff")

define athlete = Character("Atlas")
define baker = Character("Blake")
define banker = Character("Banner")
define caregiver = Character("Carol")
define guide = Character("Guy")
define janitor = Character("Janet")
define lawyer = Character("Luke")
define student = Character("Stewie")
define surgeon = Character("Susan")
define teacher = Character("Téa")
define veteran = Character("Victor")
